# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJrD0RzbBRALThXsOhEZglvvAFsdloYz
"""

import os
from flask import Flask, request, jsonify
import joblib
import pandas as pd

app = Flask(__name__)

# Fix model path for deployment
model_path = "/content/random_forest_model.pkl" # Changed to direct path using absolute path
model = joblib.load(model_path)

@app.route('/')
def home():
    return "API is live!"

@app.route('/predict', methods=['POST'])
def predict():
    data = request.get_json()
    df = pd.DataFrame([data])

    prediction = model.predict(df)[0]

    return jsonify({
        "prediction": int(prediction)
    })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=10000)